spring.application.name=todo

# import secret file
spring.config.import=optional:classpath:application-secret.properties


# Google OAuth
spring.security.oauth2.client.registration.google.scope=openid,email,profile


# Database
spring.datasource.url=jdbc:h2:file:./data/todo-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console